manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/petejohanson
    - name: zmkmouse
  projects:
    - name: zmk
      remote: zmkmouse
      revision: feat/pointers-move-scroll
      import: app/west.yml
  self:
    path: config
